#
#  Bedwars plugin by Lunoro.
#

#Game wont start if true.
startInBuildingMode: true

stopServerIfGameIsOver: true

worldName: "worldName"

maxPlayersInATeam: 2

#Amount of players it will take to start the game.
playerCountToStart: 2