name: Bedwars
version: '${project.version}'
main: de.lunoro.bedwars.Bedwars
api-version: 1.17
authors: [Lunoro]
commands:
    forcestart:
    setlocation:
    createitemspawner:
    additemspawnerlocation:
    removeitemspawnerlocation:
    removeteam:
    createteam:
    jointeam:
    itemstacltest:
    respawnPlayer:
